name: firedart_repository
description: A DatabaseAdapter for the firebase database as used by the database_repository package
version: 1.0.1
repository: https://github.com/glassp/firedart_repository

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  database_repository: ^1.1.0
  firedart: ^0.9.0+1
  uuid: ^3.0.6
  
dev_dependencies:
  effective_dart: ^1.3.2
